[package]
name = "clash-rules"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
blake2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"
num-bigint = "0.4.3"
num-traits = "0.2.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
