# Use xelatex
$pdf_mode = 5;
$xelatex_silent_switch = "-interaction=batch-mode";

# Use evince as pdf previewer
$pdf_previewer = "evince";

# Save output pdf to directory 'lmkbuild/'
$out_dir = "lmkbuild";

# Read from these files to compile pdf, elements in arrays should be separated
# by commas.
@default_files = ('main.tex');

# vim: ft=perl:
