creation_rules:
  - path_regex: morty/.*
    age: age17rhy32g9t89kspazenx4mtx74vy7e78rvq320u27k5tqmfmszv9qatg4d4
  - path_regex: rpi/.*
    age: age1wl5we8e8n3p77j8qm5fv9np8hz4ayv7vfduwpnuf577lex6l2cls3y70sc
  - path_regex: cube/*
    age: age1kul2xj4dc3vgeqg9ls2pkfy0tex93stz0n5wzv0quvexhhwjhcpssttqyn
  - path_regex: peterpan/*
    age: age1nk4n332ht4hpqyxkt4tnk4fecgrhemf5e0yk6zs9sut820zj8q9q4yqe0k
  - path_regex: cindy/*
    age: age1cacy7w6e0cln0xhje8n2wrq3lxhqhkf5gjjc3erhst39fnv3hggscqzq84
  - path_regex: trigo/*
    age: age1mec8red6693vtv0nvg7zcdksnp45r5mvlhg20dymrmktc2q574lscydt8v
  - path_regex: tetra/*
    age: age1wt0h9vupmk5sgmt5jq35j0ee3z7mmsrsg89g48z4u8hs3fkg6c6s5g84gg
