{
  domain = [
    # base domains can be used safely since ads are blocked in earlier rules
    "domain:bing.com"
    "domain:bing.com.cn"
    "domain:bing.net"
    "domain:bingads.com"
    "domain:bingagencyawards.com"
    "domain:bingapistatistics.com"
    "domain:bingsandbox.com"
    "domain:bingvisualsearch.com"
    "domain:bingworld.com"
    "domain:bluehatnights.com"
    "domain:dictate.ms"
    "domain:live.com"
    "domain:flipwithsurface.com"
    "domain:masalladeloslimites.com"
    "domain:microsoft-give.com"
    "domain:microsoftcloudsummit.com"
    "domain:microsoftdiplomados.com"
    "domain:microsoftlatamholiday.com"
    "domain:microsoftmxfilantropia.com"
    "domain:microsoftpartnersolutions.com"
    "domain:msunlimitedcloudsummit.com"
    "domain:renovacionoffice.com"
    "domain:sprinklesapp.com"

    "domain:azure.com"
    "domain:oaistatic.com"
    "domain:oaiusercontent.com"
    "domain:openai.com"
    "domain:chatgpt.com"
    "domain:intercom.io"
    "domain:intercomcdn.com"
    "domain:ai.com"
    "domain:claude.ai"
    "domain:anthropic.com"

    "domain:bard.google.com"
    "domain:gemini.google.com"
    "domain:aistudio.google.com"
    "domain:makersuite.google.com"
    "domain:ai.google.dev"
    "domain:idx.dev"
    "domain:generativelanguage.googleapis.com"

    "domain:open.ai"
  ];
  outboundTag = "direct:ai-assistants";
}
