[package]
name = "sing-box-rules"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
blake2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
num-bigint = "0.4"
num-traits = "0.2"
serde_json = "1.0"
hex = "0.4"
log = "0.4.22"
env_logger = "0.11.5"
reqwest = "0.12.5"
infer = "0.16.0"
