# To update, run `nix run github:berberman/nvfetcher`

[apple-color-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji.ttf"

[fcitx5-fluent-dark-theme]
src.git = "https://github.com/Reverier-Xu/FluentDark-fcitx5"
fetch.github = "Reverier-Xu/FluentDark-fcitx5"

[fcitx5-sogou-themes]
src.git = "https://github.com/sxqsfun/fcitx5-sogou-themes"
fetch.github = "sxqsfun/fcitx5-sogou-themes"

[harmonyos-sans]
src.git = "https://gitee.com/openharmony/resources"
fetch.git = "https://gitee.com/openharmony/resources"

[libime-history-merge]
src.github_tag = "blurgyy/libime-history-merge"
fetch.github = "blurgyy/libime-history-merge"
cargo_locks = ["Cargo.lock"]

[lsp-format-nvim]
src.github = "lukas-reineke/lsp-format.nvim"
fetch.github = "lukas-reineke/lsp-format.nvim"

[rathole]
src.github = "rapiz1/rathole"
fetch.github = "rapiz1/rathole"
cargo_locks = ["Cargo.lock"]

[symbols-nerd-font]
src.github = "ryanoasis/nerd-fonts"
fetch.url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf"

[vscode-codicons]
src.github = "microsoft/vscode-codicons"
fetch.github = "microsoft/vscode-codicons"

[ttf-google-sans]
src.git = "https://github.com/sahibjotsaggu/Google-Sans-Fonts"
fetch.github = "sahibjotsaggu/Google-Sans-Fonts"

[zellij-hirr]
src.github = "zellij-org/zellij"
fetch.github = "zellij-org/zellij"
