# To update, run `nix run github:berberman/nvfetcher`

[alcn-repo]
src.git = "https://github.com/archlinuxcn/repo"
fetch.github = "archlinuxcn/repo"

[adobe-flash-player]
src.cmd = "echo 20220331041116"
fetch.url = "http://web.archive.org/web/20220331041116/https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz"

[alist]
src.github = "alist-org/alist"
fetch.github = "alist-org/alist"

[apple-color-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji.ttf"

[bat-theme-catppuccin]
src.git = "https://github.com/catppuccin/bat"
fetch.git = "https://github.com/catppuccin/bat"

[dms]
src.github = "anacrolix/dms"
fetch.github = "anacrolix/dms"

[dt]
src.github = "blurgyy/dt"
fetch.github = "blurgyy/dt"
cargo_locks = ["Cargo.lock"]

[dnsmasq-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[fcitx5-fluent-dark-theme]
src.git = "https://github.com/Reverier-Xu/FluentDark-fcitx5"
fetch.github = "Reverier-Xu/FluentDark-fcitx5"

[fcitx5-sogou-themes]
src.git = "https://github.com/sxqsfun/fcitx5-sogou-themes"
fetch.github = "sxqsfun/fcitx5-sogou-themes"

[fedora-virtio-win-iso]
src.cmd = "curl -I https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio | grep -i '^location:' | awk -F/ '{ print $NF }' | sed -Ee 's/virtio-win-//'"
fetch.url = "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso"

[fish-plugin-tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[fish-plugin-catppuccin]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[fonts-collection]
src.git = "https://github.com/dolbydu/font"
fetch.github = "dolbydu/font"

[foot-theme-catppuccin]
src.git = "https://github.com/catppuccin/foot"
fetch.git = "https://github.com/catppuccin/foot"

[gdb-dashboard]
src.github_tag = "cyrus-and/gdb-dashboard"
fetch.github = "cyrus-and/gdb-dashboard"

[gsfonts]
src.github = "ArtifexSoftware/urw-base35-fonts"
fetch.github = "ArtifexSoftware/urw-base35-fonts"

[harmonyos-sans]
src.git = "https://gitee.com/openharmony/resources"
fetch.git = "https://gitee.com/openharmony/resources"

[imgviz]
src.pypi = "imgviz"
fetch.pypi = "imgviz"

[import-ply-as-verts-for-blender]
src.github_tag = "TombstoneTumbleweedArt/import-ply-as-verts"
fetch.github = "TombstoneTumbleweedArt/import-ply-as-verts"

[labelme]
src.pypi = "labelme"
fetch.pypi = "labelme"

[libime-history-merge]
src.github_tag = "blurgyy/libime-history-merge"
fetch.github = "blurgyy/libime-history-merge"
cargo_locks = ["Cargo.lock"]

[loyalsoldier-geoip]
src.github = "loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geoip.dat"

[loyalsoldier-geosite]
src.github = "loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geosite.dat"

[luarock-dbus_proxy]
src.github_tag = "stefano-m/lua-dbus_proxy"
fetch.github = "stefano-m/lua-dbus_proxy"

[mayo]
src.git = "https://github.com/fougue/mayo"
fetch.github = "fougue/mayo"

[nftables-geoip-db]
src.cmd = "curl -L https://db-ip.com/db/download/ip-to-country-lite | grep 'Download IP to Country Lite CSV' | sed -Ee 's|^.*https://download.db-ip.com/free/dbip-country-lite-([0-9]{4}-[0-9]{2}).csv.gz.*$|\\1|'"
fetch.url = "https://download.db-ip.com/free/dbip-country-lite-$ver.csv.gz"

[primitive]
src.git = "https://github.com/fogleman/primitive"
fetch.github = "fogleman/primitive"

[pypipe]
src.git = "https://github.com/bugen/pypipe"
fetch.git = "https://github.com/bugen/pypipe"

[rssbot]
src.cmd = "echo v2.0.0-alpha.11"
fetch.github = "iovxw/rssbot"
cargo_locks = ["Cargo.lock"]

[sc-fonts]
src.git = "https://github.com/Haixing-Hu/latex-chinese-fonts"
fetch.github = "Haixing-Hu/latex-chinese-fonts"

[simple-icons]
src.github = "simple-icons/simple-icons-font"
fetch.url = "https://github.com/simple-icons/simple-icons-font/releases/download/$ver/simple-icons-font-$ver.zip"

[symbols-nerd-font]
src.github = "ryanoasis/nerd-fonts"
fetch.url = "https://github.com/ryanoasis/nerd-fonts/releases/download/$ver/NerdFontsSymbolsOnly.zip"

[tdesktop-lily]
src.cmd = "curl -L 'https://github.com/archlinuxcn/repo/raw/master/archlinuxcn/telegram-desktop-lily/PKGBUILD' | grep '^pkgver=' | sed -Ee 's/^pkgver=/v/'"
fetch.github = "telegramdesktop/tdesktop"
git.fetchSubmodules = true

[telegram-send]
src.pypi = "telegram-send"
fetch.pypi = "telegram-send"

[tinytools]
src.github_tag = "blurgyy/tinytools"
fetch.github = "blurgyy/tinytools"
cargo_locks = ["Cargo.lock"]

[tmux-plugin-catppuccin]
src.cmd = "echo e7b50832f9bc59b0b5ef5316ba2cd6f61e4e22fc"
fetch.github = "catppuccin/tmux"

[tro]
src.github_tag = "MichaelAquilina/tro"
fetch.github = "MichaelAquilina/tro"

[video-compare]
src.github = "pixop/video-compare"
fetch.github = "pixop/video-compare"

[vim-plugin-fcitx5-ui-nvim]
src.git = "https://github.com/black-desk/fcitx5-ui.nvim"
fetch.github = "black-desk/fcitx5-ui.nvim"

[vim-plugin-tiny-inline-diagnostic-nvim]
src.git = "https://github.com/rachartier/tiny-inline-diagnostic.nvim"
fetch.github = "rachartier/tiny-inline-diagnostic.nvim"

[vscode-codicons]
src.github = "microsoft/vscode-codicons"
fetch.url = "https://github.com/microsoft/vscode-codicons/releases/download/$ver/codicon.ttf"

[v2ray-rules-dat]
src.git = "https://github.com/loyalsoldier/v2ray-rules-dat"
src.branch = "release"
fetch.github = "loyalsoldier/v2ray-rules-dat"

[waypoint]
src.git = "https://github.com/tadeokondrak/waypoint"
fetch.github = "tadeokondrak/waypoint"
cargo_locks = ["Cargo.lock"]

[xtables-addons-perl-scripts]
# curl https://inai.de/projects/xtables-addons/ | grep -i 'Latest release:' | sed -Ee 's:.*<b>([0-9]+\.[0-9]+)</b>.*:\1:'
src.cmd = "curl https://inai.de/projects/xtables-addons/ | grep -i 'Latest release:' | sed -Ee 's:.*<b>([0-9]+\\.[0-9]+)</b>.*:\\1:'"
fetch.url = "https://inai.de/files/xtables-addons/xtables-addons-$ver.tar.xz"

[zellij-hirr]
src.github = "zellij-org/zellij"
fetch.github = "zellij-org/zellij"
cargo_locks = ["Cargo.lock"]
